import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata = {
  title: "cooperative taska sarghini",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" flex flex-col justify-between  ">
          <Navbar/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
